sonar.projectKey=pokemon-api
sonar.projectName=Pokemon Card Trading API
sonar.sources=src/app
sonar.tests=src/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=test-results/coverage.xml
sonar.sourceEncoding=UTF-8
